# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hojunester
tagline:          'A New Blog'
url:              https://hojunester.github.io
shorturl:         hojunester.github.io
paginate:         5
baseurl:          /

author:
  name:           'Hojunester'
  url:            http://hojunester.wordpress.com
  email:          hojunester@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           github.com/hojunester/hojunester.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
