# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hojunester
tagline:          A Tiny Blog
url:              https://hojunester.github.io
paginate:         5
baseurl:          /
author: 
  name:           Hojune Kim
  url:            http://hojunester.wordpress.com
  email:          hojunester@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
pages_list:
  About:  '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
